/**
 * File: FileManager.java
 * Authors: Steven Phung, Daniel Tripp, Joseph Freedman
 * Class: CECS-544-01 - Software Test and Verification
 * 
 * Assignment: Semester Project
 * Due Date: April 20, 2022 @ 5pm
 * 
 * Purpose: This is the MainFrame which will contain all other panes and frames.
 */
package filemanager;

import java.io.File;

public class MainFrame extends javax.swing.JFrame {

//    private ArrayList<splitPanes> = new ArrayList<splitPanes>;
    
    public MainFrame() {
        initComponents();
        initProperties();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutDialog = new javax.swing.JDialog();
        button_OK = new javax.swing.JButton();
        panel_About_ProgramName = new javax.swing.JPanel();
        label_About_ProgramName = new javax.swing.JLabel();
        panel_About_Names = new javax.swing.JPanel();
        label_About_Names = new javax.swing.JLabel();
        panel_Main = new javax.swing.JPanel();
        panel_Toolbar = new javax.swing.JPanel();
        comboBox_Drives = new javax.swing.JComboBox<>();
        button_Details = new javax.swing.JButton();
        button_Simple = new javax.swing.JButton();
        panel_Statusbar = new javax.swing.JPanel();
        label_Status = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menu_File = new javax.swing.JMenu();
        menuItem_Rename = new javax.swing.JMenuItem();
        menuItem_Copy = new javax.swing.JMenuItem();
        menuItem_Delete = new javax.swing.JMenuItem();
        menuItem_Run = new javax.swing.JMenuItem();
        menuItem_Exit = new javax.swing.JMenuItem();
        menu_Tree = new javax.swing.JMenu();
        menuItem_Expand = new javax.swing.JMenuItem();
        menuItem_Collapse = new javax.swing.JMenuItem();
        menu_Window = new javax.swing.JMenu();
        menuItem_New = new javax.swing.JMenuItem();
        menuItem_Cascade = new javax.swing.JMenuItem();
        menu_Help = new javax.swing.JMenu();
        menuItem_Help = new javax.swing.JMenuItem();
        menuItem_About = new javax.swing.JMenuItem();

        aboutDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        aboutDialog.setTitle("About");
        aboutDialog.setMinimumSize(new java.awt.Dimension(500, 250));
        aboutDialog.setModal(true);
        aboutDialog.setPreferredSize(new java.awt.Dimension(500, 250));

        button_OK.setText("OK");
        button_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_OKActionPerformed(evt);
            }
        });

        label_About_ProgramName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_About_ProgramName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_About_ProgramName.setText("CECS 544 File Manager");

        javax.swing.GroupLayout panel_About_ProgramNameLayout = new javax.swing.GroupLayout(panel_About_ProgramName);
        panel_About_ProgramName.setLayout(panel_About_ProgramNameLayout);
        panel_About_ProgramNameLayout.setHorizontalGroup(
            panel_About_ProgramNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_About_ProgramNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_About_ProgramName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_About_ProgramNameLayout.setVerticalGroup(
            panel_About_ProgramNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_About_ProgramNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_About_ProgramName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label_About_Names.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_About_Names.setText("Copyright (c) 2022 : Steven Phung, Daniel Tripp, Joseph Freedman");

        javax.swing.GroupLayout panel_About_NamesLayout = new javax.swing.GroupLayout(panel_About_Names);
        panel_About_Names.setLayout(panel_About_NamesLayout);
        panel_About_NamesLayout.setHorizontalGroup(
            panel_About_NamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_About_NamesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_About_Names, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_About_NamesLayout.setVerticalGroup(
            panel_About_NamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_About_NamesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_About_Names)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout aboutDialogLayout = new javax.swing.GroupLayout(aboutDialog.getContentPane());
        aboutDialog.getContentPane().setLayout(aboutDialogLayout);
        aboutDialogLayout.setHorizontalGroup(
            aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutDialogLayout.createSequentialGroup()
                        .addComponent(button_OK)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panel_About_ProgramName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_About_Names, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        aboutDialogLayout.setVerticalGroup(
            aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_About_ProgramName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_About_Names, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(button_OK)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CECS 544 - File Manager");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        panel_Toolbar.setMinimumSize(new java.awt.Dimension(1280, 50));

        comboBox_Drives.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBox_Drives.setMinimumSize(new java.awt.Dimension(200, 38));
        comboBox_Drives.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboBox_DrivesPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                comboBox_DrivesPopupMenuWillBecomeVisible(evt);
            }
        });

        button_Details.setText("Details");
        button_Details.setMinimumSize(new java.awt.Dimension(100, 38));

        button_Simple.setText("Simple");
        button_Simple.setMinimumSize(new java.awt.Dimension(100, 38));

        javax.swing.GroupLayout panel_ToolbarLayout = new javax.swing.GroupLayout(panel_Toolbar);
        panel_Toolbar.setLayout(panel_ToolbarLayout);
        panel_ToolbarLayout.setHorizontalGroup(
            panel_ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ToolbarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comboBox_Drives, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_Simple, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(430, 430, 430))
        );
        panel_ToolbarLayout.setVerticalGroup(
            panel_ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Details, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(button_Simple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBox_Drives, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel_Statusbar.setMinimumSize(new java.awt.Dimension(1280, 16));
        panel_Statusbar.setPreferredSize(new java.awt.Dimension(1280, 16));

        label_Status.setMinimumSize(new java.awt.Dimension(1280, 16));
        label_Status.setPreferredSize(new java.awt.Dimension(1280, 16));

        javax.swing.GroupLayout panel_StatusbarLayout = new javax.swing.GroupLayout(panel_Statusbar);
        panel_Statusbar.setLayout(panel_StatusbarLayout);
        panel_StatusbarLayout.setHorizontalGroup(
            panel_StatusbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_StatusbarLayout.setVerticalGroup(
            panel_StatusbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_StatusbarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panel_MainLayout = new javax.swing.GroupLayout(panel_Main);
        panel_Main.setLayout(panel_MainLayout);
        panel_MainLayout.setHorizontalGroup(
            panel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_Statusbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_MainLayout.setVerticalGroup(
            panel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_MainLayout.createSequentialGroup()
                .addComponent(panel_Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 631, Short.MAX_VALUE)
                .addComponent(panel_Statusbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menu_File.setText("File");

        menuItem_Rename.setText("Rename");
        menu_File.add(menuItem_Rename);

        menuItem_Copy.setText("Copy");
        menu_File.add(menuItem_Copy);

        menuItem_Delete.setText("Delete");
        menu_File.add(menuItem_Delete);

        menuItem_Run.setText("Run");
        menu_File.add(menuItem_Run);

        menuItem_Exit.setText("Exit");
        menuItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_ExitActionPerformed(evt);
            }
        });
        menu_File.add(menuItem_Exit);

        menuBar.add(menu_File);

        menu_Tree.setText("Tree");

        menuItem_Expand.setText("Expand Branch");
        menu_Tree.add(menuItem_Expand);

        menuItem_Collapse.setText("Collapse Branch");
        menu_Tree.add(menuItem_Collapse);

        menuBar.add(menu_Tree);

        menu_Window.setText("Window");

        menuItem_New.setText("New Window");
        menu_Window.add(menuItem_New);

        menuItem_Cascade.setText("Cascade Windows");
        menu_Window.add(menuItem_Cascade);

        menuBar.add(menu_Window);

        menu_Help.setText("Help");

        menuItem_Help.setText("Help");
        menu_Help.add(menuItem_Help);

        menuItem_About.setText("About");
        menuItem_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_AboutActionPerformed(evt);
            }
        });
        menu_Help.add(menuItem_About);

        menuBar.add(menu_Help);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Clicking Menu's File > Exit exits program
    private void menuItem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_ExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuItem_ExitActionPerformed

    //Clicking Menu's Help > About creates About dialog box 
    private void menuItem_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_AboutActionPerformed
        aboutDialog.setLocationRelativeTo(null);
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_menuItem_AboutActionPerformed

    //Destroys About dialog box
    private void button_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_OKActionPerformed
        aboutDialog.dispose();
    }//GEN-LAST:event_button_OKActionPerformed

    //Opening combo box menu will update drivers
    private void comboBox_DrivesPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboBox_DrivesPopupMenuWillBecomeVisible
        //Gets currently selected item
        Object selectedItem = comboBox_Drives.getSelectedItem().toString();
        //Reloads
        reloadDrivers();
        //Displays previously selected item if new item not selected
        comboBox_Drives.setSelectedItem(selectedItem);
    }//GEN-LAST:event_comboBox_DrivesPopupMenuWillBecomeVisible

    //Closing combo box will select drive
    private void comboBox_DrivesPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboBox_DrivesPopupMenuWillBecomeInvisible
        if(comboBox_Drives.getSelectedItem() != null) {
            System.out.println(String.valueOf(comboBox_Drives.getSelectedItem()));
            updateStatus();
        }
    }//GEN-LAST:event_comboBox_DrivesPopupMenuWillBecomeInvisible

    //Initializes features and properties needed for main frame
    private void initProperties() {
        //Load drivers in comboBox
        reloadDrivers();
        //Initialize status bar
        updateStatus();
        //Shows window
        this.setVisible(true);
    }
    
    //Updates status bar based on currently selected drive
    public void updateStatus() {
        String selectedDrive = String.valueOf(comboBox_Drives.getSelectedItem());   
        File[] drives = File.listRoots();
        for (File drive : drives) {   
            if(String.valueOf(drive).equals(selectedDrive)) {
                long freeSpace = drive.getFreeSpace()/(1024*1024*1024);
                long totalSpace = drive.getTotalSpace()/(1024*1024*1024);
                long usedSpace = totalSpace - freeSpace;
                label_Status.setText("Current Drive: " + drive + "     Free Space: " + freeSpace + "GB     Used Space: " + usedSpace + "GB     Total Space: " + totalSpace + "GB");
            }
        }
    }
    
    //Reloads drivers in combobox
    private void reloadDrivers() {
        comboBox_Drives.removeAllItems();
        File[] paths = File.listRoots();
        for(File path:paths) {
            comboBox_Drives.addItem(path.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog aboutDialog;
    private javax.swing.JButton button_Details;
    private javax.swing.JButton button_OK;
    private javax.swing.JButton button_Simple;
    private javax.swing.JComboBox<String> comboBox_Drives;
    private javax.swing.JLabel label_About_Names;
    private javax.swing.JLabel label_About_ProgramName;
    private javax.swing.JLabel label_Status;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItem_About;
    private javax.swing.JMenuItem menuItem_Cascade;
    private javax.swing.JMenuItem menuItem_Collapse;
    private javax.swing.JMenuItem menuItem_Copy;
    private javax.swing.JMenuItem menuItem_Delete;
    private javax.swing.JMenuItem menuItem_Exit;
    private javax.swing.JMenuItem menuItem_Expand;
    private javax.swing.JMenuItem menuItem_Help;
    private javax.swing.JMenuItem menuItem_New;
    private javax.swing.JMenuItem menuItem_Rename;
    private javax.swing.JMenuItem menuItem_Run;
    private javax.swing.JMenu menu_File;
    private javax.swing.JMenu menu_Help;
    private javax.swing.JMenu menu_Tree;
    private javax.swing.JMenu menu_Window;
    private javax.swing.JPanel panel_About_Names;
    private javax.swing.JPanel panel_About_ProgramName;
    private javax.swing.JPanel panel_Main;
    private javax.swing.JPanel panel_Statusbar;
    private javax.swing.JPanel panel_Toolbar;
    // End of variables declaration//GEN-END:variables
}
